apiVersion: v1
kind: Service
metadata:
  name: storage
  namespace: qwep-data-fortress
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30970
  selector:
    app: storage
